apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: open-webui
  name: ollama-webui-pvc
  labels:
    app: ollama-webui
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  # volumeMode: Filesystem
